### ISSUE TITLE
Github Track Courses to be Completed

### ISSUE THREAD

**Issue by Richardr92** [Richardr92/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Github Track*

* [ ] Working by yourself
* [ ] Working on a team
* [ ] create a Web Presence on GitHub
* [ ] Get Involved in Open Source

🎉 🙆‍♂️ 🎊 

cc @Richardr92
